import type { CaseStudy } from '@/types/content';

export const caseStudies: CaseStudy[] = [
  {
    slug: 'digital-media-at-scale',
    title: 'Digital Media at Scale',
    company: 'BHM / ID Africa / NET',
    year: '2016–2018',
    industry: ['Digital Media', 'Web Infrastructure', 'Advertising'],
    categories: ['Digital Operations', 'Infrastructure', 'Monetization', 'SEO'],
    tagline: 'Digital Infrastructure × Monetization',
    challenge:
      'Managing a portfolio of digital platforms, servers, advertising infrastructure, social channels and commercial assets required coordination across technology, audience, content and revenue.',
    environment: [
      '20+ web platforms',
      '6 servers',
      'Advertising infrastructure',
      'Social channels',
    ],
    role: 'Digital Infrastructure & Monetization Lead',
    intervention: [
      'Infrastructure management',
      'SEO',
      'Advertising technology',
      'Analytics',
      'Social monetization',
      'Revenue management',
      'Project coordination',
      'Vendor/developer coordination',
    ],
    systems: ['CMS', 'Ad Tech', 'Server Infrastructure', 'Analytics Platform'],
    flow: [
      'AUDIENCE',
      'CONTENT',
      'PLATFORM',
      'TRAFFIC',
      'DATA',
      'ADVERTISING',
      'REVENUE',
    ],
    outcomes: [
      'A more integrated digital operating model connecting audience, infrastructure, content and revenue.',
    ],
    capabilities: [
      'Web Infrastructure',
      'Advertising Technology',
      'Monetization',
      'SEO',
      'Analytics',
      'Project Leadership',
      'Vendor Management',
      'Revenue Management',
    ],
    relatedSlugs: ['digital-asset-monetization', 'iroko-digital-content-engine'],
    featured: true,
    order: 1,
  },
  {
    slug: 'iroko-digital-content-engine',
    title: 'Building the Digital Engine of Streaming',
    company: 'iROKO Partners',
    year: '2011–2014',
    industry: ['Digital Media', 'Entertainment', 'Streaming'],
    categories: ['Digital Operations', 'Digital Media', 'Analytics'],
    tagline: 'Content × Technology × Data × Commercial',
    challenge:
      'Operating a large digital content ecosystem required more than cataloguing content. It required a structured operating layer connecting content quality, discoverability, performance, people and commercial activity.',
    environment: [
      'Digital content catalog',
      'Streaming platform',
      'Artiste relations',
      'Content team (11+)',
    ],
    role: 'Content Operations & Team Leadership',
    intervention: [
      'Digital content cataloguing',
      'Metadata management',
      'Content performance analytics',
      'Team leadership',
      'Content optimization',
      'Artiste relations',
      'Revenue reconciliation',
      'Business development',
    ],
    systems: ['Content Management System', 'Analytics Platform'],
    flow: [
      'CONTENT',
      'METADATA',
      'DISCOVERABILITY',
      'PERFORMANCE',
      'ANALYTICS',
      'REVENUE',
    ],
    outcomes: [
      'A more structured operating layer connecting content quality, discoverability, performance, people and commercial activity.',
      'Trained and managed 11+ content professionals.',
    ],
    capabilities: [
      'Content Operations',
      'Digital Asset Management',
      'Analytics',
      'Team Leadership',
      'Business Development',
      'Data Interpretation',
    ],
    relatedSlugs: ['digital-media-at-scale', 'digital-asset-monetization'],
    featured: true,
    order: 2,
  },
  {
    slug: 'logistics-transformation',
    title: 'Logistics Transformation',
    company: 'Official Shoppers Warehouse',
    year: '2025',
    industry: ['Logistics', 'Supply Chain', 'FMCG', 'Distribution'],
    categories: ['Logistics', 'Supply Chain', 'Fleet', 'Analytics'],
    tagline: 'Logistics × Data × Technology × Cost',
    challenge:
      'A complex multi-category distribution environment required stronger visibility, control and performance management across the physical operating system.',
    environment: [
      'Logistics',
      'FMCG',
      'Electronics',
      'Homewares',
      'Beverages',
    ],
    role: 'Supply Chain & Distribution Operations',
    intervention: [
      'TMS implementation',
      'GPS fleet tracking',
      'Fuel monitoring',
      'Route optimization',
      'KPI dashboards',
      'ERP integration',
      'Team performance systems',
      'Supply-chain optimization',
    ],
    systems: ['TMS', 'GPS Fleet Tracking', 'ERP', 'WMS', 'KPI Dashboards'],
    flow: [
      'FLEET DATA',
      'ROUTE ANALYSIS',
      'TMS',
      'GPS',
      'FUEL CONTROL',
      'KPI DASHBOARD',
      'COST REDUCTION',
    ],
    outcomes: [
      'Transformed a complex multi-category distribution environment into a measurable, technology-enabled operating system.',
    ],
    metrics: [
      { value: '20%+', label: 'Operational Growth', context: 'Year-over-year' },
      { value: '>95%', label: 'OTIF Performance', context: 'On-time, in-full' },
      { value: '20%', label: 'Lower Cost-per-Delivery', context: 'Reduction' },
      { value: '25%', label: 'Lower Fuel Expense', context: 'Reduction' },
      { value: '35%', label: 'Operational Efficiency', context: 'Improvement' },
    ],
    capabilities: [
      'Fleet Management',
      'Route Optimization',
      'Last-Mile Delivery',
      'Supply Chain',
      'Warehouse Operations',
      'Compliance',
      'Team Leadership',
      'KPI Design',
      'Performance Monitoring',
      'P&L Exposure',
    ],
    relatedSlugs: ['topcheck-fintech-operations', 'digital-media-at-scale'],
    featured: true,
    order: 3,
  },
  {
    slug: 'topcheck-fintech-operations',
    title: 'Turning Fintech Operations into a Digital Customer Journey',
    company: 'TopCheck',
    year: '2015–2016',
    industry: ['Fintech', 'Insurance'],
    categories: ['Fintech', 'Digital Operations', 'Analytics'],
    tagline: 'Fintech × Insurance × Digital Operations',
    challenge:
      'The work sat at the intersection of regulated processes, digital customer journeys, commercial relationships and operational execution.',
    environment: [
      'Insurance digitization',
      'Vendor relationships',
      'Digital customer journey',
    ],
    role: 'Operations & Digital',
    intervention: [
      'Operations',
      'Insurance digitization',
      'Business research',
      'Analytics',
      'Marketing',
      'Vendor relationships',
      'Insurance-company onboarding',
      'Renewals',
    ],
    systems: ['Digital Platform', 'Analytics'],
    flow: [
      'RESEARCH',
      'PARTNER ONBOARDING',
      'DIGITAL JOURNEY',
      'OPERATIONS',
      'RENEWALS',
      'PERFORMANCE',
    ],
    outcomes: [
      'Translated a regulated business process into a digital customer journey connecting partner onboarding, operations and renewals.',
    ],
    capabilities: [
      'Business Operations',
      'Vendor Management',
      'Analytics',
      'SEO',
      'Digital Marketing',
      'Business Development',
    ],
    relatedSlugs: ['logistics-transformation', 'digital-asset-monetization'],
    featured: true,
    order: 4,
  },
  {
    slug: 'digital-asset-monetization',
    title: 'From Audience to Revenue',
    company: 'ZedOut / BHM / NET / LoveWorld',
    year: '2016–Present',
    industry: ['Digital Media', 'Consulting', 'Monetization'],
    categories: ['Monetization', 'Digital Media', 'SEO', 'Digital Operations'],
    tagline: 'Digital Assets × Audience × Monetization',
    challenge:
      'Digital platforms are often treated as publishing destinations rather than commercial assets. The work required connecting audience development, content systems, search visibility, analytics, advertising infrastructure and monetization.',
    environment: [
      'Digital asset portfolio',
      'Audience platforms',
      'Advertising infrastructure',
    ],
    role: 'Digital Asset Management & Monetization',
    intervention: [
      'Audience development',
      'Content systems',
      'Search visibility (SEO)',
      'Analytics',
      'Advertising infrastructure',
      'Monetization strategy',
    ],
    systems: ['CMS', 'Ad Tech', 'Analytics Platform'],
    flow: [
      'AUDIENCE',
      'CONTENT',
      'TRAFFIC',
      'DATA',
      'ADVERTISING',
      'MONETIZATION',
      'REVENUE',
    ],
    outcomes: [
      'Connected audience development, content systems, search visibility, analytics, advertising infrastructure and monetization into a single commercial system.',
    ],
    capabilities: [
      'Digital Asset Management',
      'Monetization',
      'SEO',
      'Analytics',
      'Advertising Technology',
      'Revenue Management',
    ],
    relatedSlugs: ['digital-media-at-scale', 'iroko-digital-content-engine'],
    featured: true,
    order: 5,
  },
];

export const getCaseStudy = (slug: string): CaseStudy | undefined =>
  caseStudies.find((cs) => cs.slug === slug);

export const getFeaturedCaseStudies = (): CaseStudy[] =>
  caseStudies.filter((cs) => cs.featured).sort((a, b) => a.order - b.order);
