import type { Experience } from '@/types/content';

export const experiences: Experience[] = [
  {
    id: 'tastee',
    company: 'Tastee Fried Chicken',
    role: 'Sales & Operations',
    startDate: '2009',
    endDate: '2011',
    industry: ['Food & Beverage', 'Retail'],
    era: 'Commercial Foundations',
    eraPeriod: '2009–2011',
    focus: [
      'Sales',
      'Profitability',
      'Quality control',
      'Operational reporting',
      'Customer-facing execution',
    ],
    responsibilities: [
      'Customer-facing sales and service execution',
      'Quality control across food preparation and presentation',
      'Operational reporting on sales performance and profitability',
    ],
    achievements: [
      'Built commercial awareness close to the customer transaction',
      'Developed foundational discipline in operational reporting',
    ],
    capabilities: [
      'Business Operations',
      'Process Optimization',
      'Customer Experience',
      'Quality Control',
    ],
    verified: true,
  },
  {
    id: 'iroko',
    company: 'iROKO Partners',
    role: 'Content Operations & Team Leadership',
    startDate: '2011',
    endDate: '2014',
    industry: ['Digital Media', 'Entertainment', 'Streaming'],
    era: 'Digital Content & Media Systems',
    eraPeriod: '2011–2014',
    focus: [
      'Content operations',
      'Metadata',
      'Analytics',
      'Team leadership',
      'Digital asset management',
      'Artiste relations',
      'Revenue reconciliation',
      'Business development',
    ],
    responsibilities: [
      'Digital content cataloguing and metadata management',
      'Content performance analytics and optimization',
      'Team leadership across content operations',
      'Artiste relations and content partnerships',
      'Revenue reconciliation and business development',
    ],
    achievements: [
      'Trained and managed 11+ content professionals',
      'Built a structured operating layer connecting content quality, discoverability, performance and commercial activity',
    ],
    capabilities: [
      'Content Operations',
      'Digital Asset Management',
      'Analytics',
      'Team Leadership',
      'Business Development',
      'Data Interpretation',
    ],
    systems: ['Content Management System', 'Analytics Platform'],
    verified: true,
  },
  {
    id: 'topcheck',
    company: 'TopCheck',
    role: 'Operations & Digital',
    startDate: '2015',
    endDate: '2016',
    industry: ['Fintech', 'Insurance'],
    era: 'Business, Fintech & Digital Operations',
    eraPeriod: '2015–2016',
    focus: [
      'Fintech operations',
      'Insurance digitization',
      'Vendor management',
      'Research',
      'Analytics',
      'Marketing',
      'SEO',
      'Web operations',
    ],
    responsibilities: [
      'Operations across insurance digitization',
      'Business research and analytics',
      'Vendor relationships and insurance-company onboarding',
      'Marketing, SEO and web operations',
      'Renewals and performance management',
    ],
    achievements: [
      'Translated a regulated business process into a digital customer journey',
      'Connected partner onboarding, digital journey and renewals into a coherent operating flow',
    ],
    capabilities: [
      'Business Operations',
      'Vendor Management',
      'Analytics',
      'SEO',
      'Digital Marketing',
      'Web Operations',
      'Business Development',
    ],
    verified: true,
  },
  {
    id: 'carsinyankee',
    company: 'Carsinyankee',
    role: 'Digital Operations',
    startDate: '2015',
    endDate: '2016',
    industry: ['E-commerce', 'Automotive'],
    era: 'Business, Fintech & Digital Operations',
    eraPeriod: '2015–2016',
    focus: [
      'Digital platforms',
      'Marketing',
      'SEO',
      'Web operations',
    ],
    responsibilities: [
      'Digital platform operations',
      'Marketing and SEO execution',
      'Web operations management',
    ],
    achievements: [
      'Extended digital operations discipline into a marketplace environment',
    ],
    capabilities: [
      'Digital Marketing',
      'SEO',
      'Web Operations',
    ],
    verified: true,
  },
  {
    id: 'bhm',
    company: 'BHM Group / ID Africa / NET',
    role: 'Digital Infrastructure & Monetization Lead',
    startDate: '2016',
    endDate: '2018',
    industry: ['Digital Media', 'Advertising', 'Web Infrastructure'],
    era: 'Digital Infrastructure & Monetization',
    eraPeriod: '2016–2018',
    focus: [
      '20+ web platforms',
      '6 servers',
      'Advertising technology',
      'Monetization',
      'SEO',
      'Social platforms',
      'Web infrastructure',
      'Project management',
      'Analytics',
    ],
    responsibilities: [
      'Infrastructure management across 20+ web platforms and 6 servers',
      'SEO and advertising technology operations',
      'Social platform management and monetization',
      'Revenue management across the digital portfolio',
      'Project coordination and vendor/developer coordination',
      'Analytics and performance reporting',
    ],
    achievements: [
      'Built a more integrated digital operating model connecting audience, infrastructure, content and revenue',
      'Managed 20+ web platforms and 6 servers simultaneously',
    ],
    capabilities: [
      'Web Infrastructure',
      'Advertising Technology',
      'Monetization',
      'SEO',
      'Analytics',
      'Project Leadership',
      'Vendor Management',
      'Social Media',
      'Revenue Management',
    ],
    systems: ['CMS', 'Ad Tech Platform', 'Server Infrastructure', 'Analytics'],
    verified: true,
  },
  {
    id: 'zedout',
    company: 'ZedOut Limited',
    role: 'Consulting, Digital Assets & Operational Systems',
    startDate: '2018',
    endDate: 'Present',
    industry: ['Consulting', 'Digital Media', 'Logistics', 'E-hailing'],
    era: 'Consulting, Digital Assets & Operational Systems',
    eraPeriod: '2018–Present',
    focus: [
      'Digital asset management',
      'Reputation management',
      'SEO',
      'Digital positioning',
      'Logistics',
      'E-hailing',
      'Fleet operations',
      'Driver management',
      'Compliance',
      'Procurement',
      'Vendor management',
      'Client reporting',
      'Payouts',
    ],
    responsibilities: [
      'Digital asset management and reputation management',
      'SEO and digital positioning for clients',
      'Logistics and e-hailing fleet operations',
      'Driver management and compliance',
      'Procurement and vendor management',
      'Client reporting and payouts',
    ],
    achievements: [
      'Extended operating discipline from digital systems into physical fleet and logistics operations',
      'Built consulting practice spanning digital assets and operational systems',
    ],
    capabilities: [
      'Digital Asset Management',
      'Digital Reputation',
      'SEO',
      'Fleet Management',
      'Vendor Management',
      'Procurement',
      'Compliance',
      'Client Reporting',
      'Payouts',
    ],
    verified: true,
  },
  {
    id: 'official-shoppers',
    company: 'Official Shoppers Warehouse',
    role: 'Supply Chain & Distribution Operations',
    startDate: '2025',
    industry: ['Logistics', 'Supply Chain', 'FMCG', 'Distribution'],
    era: 'Supply Chain & Distribution',
    eraPeriod: '2025',
    focus: [
      'Logistics',
      'FMCG',
      'Electronics',
      'Homewares',
      'Beverages',
      'TMS',
      'GPS tracking',
      'ERP',
      'WMS',
      'KPI dashboards',
      'P&L',
      'Compliance',
      'Route optimization',
      'Team leadership',
    ],
    responsibilities: [
      'Logistics and multi-category distribution (FMCG, electronics, homewares, beverages)',
      'TMS implementation and GPS fleet tracking',
      'Fuel monitoring and route optimization',
      'KPI dashboards and ERP integration',
      'Team performance systems and supply-chain optimization',
      'P&L management and compliance',
    ],
    achievements: [
      'Led 15+ logistics personnel',
      '20%+ operational growth',
      '>95% OTIF performance',
      '20% reduction in cost-per-delivery',
      '25% reduction in fuel expenses',
      '35% improvement in operational efficiency',
      'Multi-million ₦ P&L exposure',
    ],
    capabilities: [
      'Fleet Management',
      'Route Optimization',
      'Last-Mile Delivery',
      'Supply Chain',
      'Warehouse Operations',
      'Compliance',
      'Team Leadership',
      'KPI Design',
      'Performance Monitoring',
      'P&L Exposure',
      'Distribution',
    ],
    systems: ['TMS', 'GPS Fleet Tracking', 'ERP', 'WMS', 'KPI Dashboards'],
    verified: true,
  },
];
