import type { MediaAsset, QuickAccessPreset } from '@/types/cms';

export const defaultQuickAccessPresets: QuickAccessPreset[] = [
  {
    id: 'preset-superadmin',
    label: 'Kel Nnorom (Super Admin)',
    email: 'superadmin@kelnnorom.com',
    role: 'super_admin',
    description: 'Master platform ownership, user accounts, database reset, and security keys.',
    badge: 'Master Key',
  },
  {
    id: 'preset-contentadmin',
    label: 'Editorial Administrator',
    email: 'admin@kelnnorom.com',
    role: 'admin',
    description: 'Full management of insights, case studies, hero banners, and media assets.',
    badge: 'Content Lead',
  },
  {
    id: 'preset-editor',
    label: 'Strategy Contributor',
    email: 'editor@kelnnorom.com',
    role: 'editor',
    description: 'Drafting essays, updating telemetry metrics, and publishing case notes.',
    badge: 'Author',
  },
  {
    id: 'preset-viewer',
    label: 'Executive Auditor / Viewer',
    email: 'auditor@kelnnorom.com',
    role: 'viewer',
    description: 'Read-only analytics telemetry and operational database inspection.',
    badge: 'Audit Only',
  },
];

export const defaultMediaAssets: MediaAsset[] = [
  {
    id: 'med-hero-1',
    title: 'High-Velocity Logistics Hub & Automated Sortation',
    filename: 'warehouse-automation-matrix.webp',
    url: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=1400&auto=format&fit=crop',
    type: 'image',
    mimeType: 'image/webp',
    sizeBytes: 482900,
    width: 1400,
    height: 788,
    aspectRatio: '16:9',
    category: 'banners',
    tags: ['Logistics', 'WMS', 'Automation', 'Supply Chain', 'Warehouse'],
    altText: 'Modern high-bay logistics distribution center with automated conveyor lines',
    caption: 'Warehouse sortation topology engineered for sub-2 hour cross-dock throughput.',
    description: 'Primary visual asset used on the logistics systems case studies and homepage hero banner.',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
    author: 'Kel Nnorom Media Archive',
    filterPreset: 'contrast',
    cropPreset: '16:9',
  },
  {
    id: 'med-hero-2',
    title: 'Fintech Transaction Flow & Clearing Topology',
    filename: 'fintech-settlement-flow.webp',
    url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1400&auto=format&fit=crop',
    type: 'image',
    mimeType: 'image/webp',
    sizeBytes: 384200,
    width: 1400,
    height: 788,
    aspectRatio: '16:9',
    category: 'insights',
    tags: ['Fintech', 'Settlement', 'Arbitrage', 'Payments', 'Telemetry'],
    altText: 'Real-time financial analytics dashboard displaying transaction latency and routing',
    caption: 'Sub-second payment settlement and route optimization topology.',
    description: 'Hero cover for the algorithmic currency corridors essay.',
    createdAt: '2024-02-01T12:30:00Z',
    updatedAt: '2024-02-01T12:30:00Z',
    author: 'Kel Nnorom Media Archive',
    filterPreset: 'cyber-blue',
    cropPreset: '16:9',
  },
  {
    id: 'med-hero-3',
    title: 'Enterprise Server Architecture & Data Backbone',
    filename: 'server-datacenter-backbone.webp',
    url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=1400&auto=format&fit=crop',
    type: 'image',
    mimeType: 'image/webp',
    sizeBytes: 612400,
    width: 1400,
    height: 788,
    aspectRatio: '16:9',
    category: 'banners',
    tags: ['Architecture', 'Cloud', 'Data Systems', 'Infrastructure'],
    altText: 'Row of illuminated high-density server racks in enterprise datacenter',
    caption: 'High-availability infrastructure backing multi-region operations.',
    description: 'Infrastructure backdrop for operating philosophy and systems pages.',
    createdAt: '2024-02-14T08:15:00Z',
    updatedAt: '2024-02-14T08:15:00Z',
    author: 'Kel Nnorom Media Archive',
    filterPreset: 'warm-gold',
    cropPreset: '16:9',
  },
  {
    id: 'med-avatar-1',
    title: 'Kel Nnorom — Official Executive Portrait',
    filename: 'kel-nnorom-executive-portrait.jpg',
    url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=800&auto=format&fit=crop',
    type: 'image',
    mimeType: 'image/jpeg',
    sizeBytes: 215000,
    width: 800,
    height: 800,
    aspectRatio: '1:1',
    category: 'avatars',
    tags: ['Portrait', 'Headshot', 'Executive', 'Profile'],
    altText: 'Kel Nnorom — Cross-Functional Operations & Growth Strategist',
    caption: 'Official executive profile portrait.',
    description: 'Primary headshot avatar for about page, author credits, and social cards.',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    author: 'Kel Nnorom Studio',
    filterPreset: 'none',
    cropPreset: '1:1',
  },
  {
    id: 'med-avatar-2',
    title: 'Editorial Team Avatar — Strategic Operations Desk',
    filename: 'editorial-team-badge.jpg',
    url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop',
    type: 'image',
    mimeType: 'image/jpeg',
    sizeBytes: 198000,
    width: 800,
    height: 800,
    aspectRatio: '1:1',
    category: 'avatars',
    tags: ['Avatar', 'Editorial', 'Team', 'Contributor'],
    altText: 'Operational Research Contributor Avatar',
    caption: 'Editorial Operations research avatar.',
    description: 'Secondary avatar for guest analysts and editorial contributors.',
    createdAt: '2024-02-10T11:00:00Z',
    updatedAt: '2024-02-10T11:00:00Z',
    author: 'Kel Nnorom Media Archive',
    filterPreset: 'none',
    cropPreset: '1:1',
  },
  {
    id: 'med-doc-1',
    title: 'Executive Whitepaper: Zero-Defect Logistics Architecture',
    filename: 'executive-brief-logistics-2026.pdf',
    url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    type: 'document',
    mimeType: 'application/pdf',
    sizeBytes: 2450000,
    category: 'documents',
    tags: ['Whitepaper', 'PDF', 'Logistics', 'Report', 'Executive Brief'],
    altText: 'Downloadable PDF Document: Operational Logistics Architecture Case Study',
    caption: '18-page comprehensive turnaround whitepaper and telemetry model.',
    description: 'Downloadable executive lead magnet for institutional logistics operators.',
    createdAt: '2024-02-20T14:00:00Z',
    updatedAt: '2024-02-20T14:00:00Z',
    author: 'Kel Nnorom & Advisory Partners',
  },
  {
    id: 'med-doc-2',
    title: 'Currency Settlement Telemetry Specification Guide',
    filename: 'fintech-clearing-spec-v2.pdf',
    url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    type: 'document',
    mimeType: 'application/pdf',
    sizeBytes: 1890000,
    category: 'documents',
    tags: ['Fintech', 'Clearing', 'API Spec', 'Protocol', 'PDF'],
    altText: 'PDF Technical Specification: Multi-Corridor FX Settlement Protocol',
    caption: 'Technical specification for sub-50ms FX cross-border clearing.',
    description: 'Technical annex provided to partner liquidity providers and bank clearing desks.',
    createdAt: '2024-02-22T09:15:00Z',
    updatedAt: '2024-02-22T09:15:00Z',
    author: 'Kel Nnorom Systems Lab',
  },
  {
    id: 'med-audio-1',
    title: 'Executive Voice Memo: The Mechanics of Margin Compression',
    filename: 'executive-memo-margin-compression.mp3',
    url: 'https://cdn.freesound.org/previews/612/612095_5674468-lq.mp3',
    type: 'audio',
    mimeType: 'audio/mpeg',
    sizeBytes: 5240000,
    durationSeconds: 420,
    category: 'insights',
    tags: ['Audio', 'Voice Memo', 'Podcast', 'Turnaround', 'Margins'],
    altText: 'Audio Podcast Recording: Kel Nnorom discussing margin turnaround strategies',
    caption: '7-minute strategic audio memo for executive founders.',
    description: 'Companion audio narration for the Margin Turnaround Masterclass essay.',
    createdAt: '2024-02-25T16:45:00Z',
    updatedAt: '2024-02-25T16:45:00Z',
    author: 'Kel Nnorom',
  },
  {
    id: 'med-video-1',
    title: 'Live Systems Walkthrough: 6-Node Architecture in Action',
    filename: 'systems-walkthrough-6-node-model.mp4',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    type: 'video',
    mimeType: 'video/mp4',
    sizeBytes: 18400000,
    durationSeconds: 15,
    width: 1920,
    height: 1080,
    aspectRatio: '16:9',
    category: 'case-studies',
    tags: ['Video', 'System Demo', 'Architecture', 'Operations', 'Telemetry'],
    altText: 'Video Demonstration of Enterprise Systems Architecture Mapping',
    caption: 'High-definition video tour of telemetry routing and inventory reconciliation.',
    description: 'Interactive video overview embedded in the case studies showcase.',
    createdAt: '2024-02-28T18:00:00Z',
    updatedAt: '2024-02-28T18:00:00Z',
    author: 'Kel Nnorom Production',
  },
  {
    id: 'med-img-case-1',
    title: 'Real-Time Dispatch Anomaly Detection Screen',
    filename: 'dispatch-anomaly-detection.webp',
    url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1200&auto=format&fit=crop',
    type: 'image',
    mimeType: 'image/webp',
    sizeBytes: 341000,
    width: 1200,
    height: 675,
    aspectRatio: '16:9',
    category: 'case-studies',
    tags: ['Analytics', 'Telemetry', 'Charts', 'Dispatch'],
    altText: 'Data charts tracking dispatch anomaly rate and delivery ETA predictions',
    caption: 'Anomaly detection telemetry dashboard with predictive driver alerts.',
    description: 'Case study telemetry visual from the last-mile logistics turnaround.',
    createdAt: '2024-01-20T12:00:00Z',
    updatedAt: '2024-01-20T12:00:00Z',
    author: 'Kel Nnorom Media Archive',
    filterPreset: 'contrast',
    cropPreset: '16:9',
  },
  {
    id: 'med-img-case-2',
    title: 'Cross-Border Supply Chain Port Terminals',
    filename: 'container-port-logistics.webp',
    url: 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?q=80&w=1200&auto=format&fit=crop',
    type: 'image',
    mimeType: 'image/webp',
    sizeBytes: 512000,
    width: 1200,
    height: 675,
    aspectRatio: '16:9',
    category: 'case-studies',
    tags: ['Freight', 'Shipping', 'Supply Chain', 'Trade'],
    altText: 'Aerial view of automated container terminal with gantry cranes',
    caption: 'Intermodal freight transfer protocol.',
    description: 'Featured in multi-corridor logistics turnaround cases.',
    createdAt: '2024-01-22T14:30:00Z',
    updatedAt: '2024-01-22T14:30:00Z',
    author: 'Kel Nnorom Media Archive',
    filterPreset: 'none',
    cropPreset: '16:9',
  },
];
