import type { SliderBannerItem, SiteSettings } from '@/types/cms';

export const defaultSliderBanners: SliderBannerItem[] = [
  {
    id: 'slider-digital-infra',
    title: 'Digital Systems & High-Velocity Infrastructure',
    eyebrow: 'DIGITAL OPERATIONS & MONETIZATION',
    headlineHighlight: 'Multi-Platform Scaling',
    description:
      'Orchestrating 20+ digital media properties, 6 enterprise server clusters, automated ad-tech yields, and SEO pipelines for millions of monthly unique visitors.',
    category: 'Digital Infrastructure',
    badgeText: 'BHM / NET / ID AFRICA',
    metricValue: '20+ Platforms',
    metricLabel: 'Managed & Monetized',
    metricContext: '6 Server Clusters',
    primaryCtaText: 'View Case Study',
    primaryCtaLink: '/work/digital-media-at-scale',
    secondaryCtaText: 'Explore Stack',
    secondaryCtaLink: '/capabilities',
    imageUrl:
      'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=1200&auto=format&fit=crop',
    tags: ['CMS Architecture', 'Server Infrastructure', 'SEO & Ad Tech', 'Audience Analytics'],
    active: true,
    order: 1,
  },
  {
    id: 'slider-logistics-fleet',
    title: 'Fleet Telemetry & Logistics Dispatch Redesign',
    eyebrow: 'LOGISTICS & SUPPLY CHAIN',
    headlineHighlight: '>95% OTIF Performance',
    description:
      'Eliminating dispatch bottlenecks, installing real-time GPS telemetry, and restructuring driver routes to reduce cost-per-delivery by 20% and fuel burn by 25%.',
    category: 'Logistics Optimization',
    badgeText: 'ZEDOUT / LOGISTICS FLEET',
    metricValue: '-25% Fuel',
    metricLabel: 'Expense Reduction',
    metricContext: '>95% On-Time In-Full',
    primaryCtaText: 'Inspect Operations',
    primaryCtaLink: '/work/warehouse-logistics-system-rebuild',
    secondaryCtaText: '6-Stage Philosophy',
    secondaryCtaLink: '/philosophy',
    imageUrl:
      'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=1200&auto=format&fit=crop',
    tags: ['GPS Telemetry', 'Route Optimization', 'Driver SLA Controls', 'Fuel Auditing'],
    active: true,
    order: 2,
  },
  {
    id: 'slider-streaming-engine',
    title: 'High-Cadence Nollywood Streaming Engine',
    eyebrow: 'DIGITAL ASSET MANAGEMENT',
    headlineHighlight: 'Content Supply Chain',
    description:
      'Building the ingestion, encoding, copyright governance, and metadata taxonomies that powered global digital distribution for African entertainment.',
    category: 'Media Streaming',
    badgeText: 'iROKO / NOLLYWOOD',
    metricValue: '11+ Operators',
    metricLabel: 'Trained & Coordinated',
    metricContext: 'Multi-Territory Ingestion',
    primaryCtaText: 'Review System',
    primaryCtaLink: '/work/iroko-digital-content-engine',
    secondaryCtaText: 'Leadership Ecosystem',
    secondaryCtaLink: '/ecosystem',
    imageUrl:
      'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?q=80&w=1200&auto=format&fit=crop',
    tags: ['Digital Asset Management', 'Video Encoding', 'Rights Governance', 'Metadata Engine'],
    active: true,
    order: 3,
  },
  {
    id: 'slider-warehouse-supply-chain',
    title: 'High-Density Warehousing & Inventory Velocity',
    eyebrow: 'SUPPLY CHAIN & COMMERCIAL P&L',
    headlineHighlight: 'Multi-Million ₦ Exposure',
    description:
      'Transforming multi-hub inventory handling, implementing FIFO pick-and-pack discipline, and stabilizing distributor replenishment cycles under volatility.',
    category: 'Supply Chain',
    badgeText: 'OFFICIAL SHOPPERS WAREHOUSE',
    metricValue: '+35% Gain',
    metricLabel: 'Operational Efficiency',
    metricContext: 'Zero Stock Discrepancies',
    primaryCtaText: 'Explore Case Study',
    primaryCtaLink: '/work/warehouse-logistics-system-rebuild',
    secondaryCtaText: 'Operating Matrix',
    secondaryCtaLink: '/experience',
    imageUrl:
      'https://images.unsplash.com/photo-1553413077-190dd305871c?q=80&w=1200&auto=format&fit=crop',
    tags: ['WMS Deployment', 'Inventory Turns', 'FIFO Tracking', 'Working Capital'],
    active: true,
    order: 4,
  },
  {
    id: 'slider-turnaround-advisory',
    title: 'Strategic Turnarounds & Operational Advisory',
    eyebrow: 'EXECUTIVE ADVISORY & SYSTEMS',
    headlineHighlight: '15+ Years Mastery',
    description:
      'Diagnosing systemic friction across commercial, technical, and human layers to build predictable, resilient operating engines for growth companies.',
    category: 'Executive Advisory',
    badgeText: 'CROSS-FUNCTIONAL STRATEGY',
    metricValue: '100% Proven',
    metricLabel: 'Documented Outcomes',
    metricContext: 'Fiduciary Integrity',
    primaryCtaText: 'Get 60-Sec Brief',
    primaryCtaLink: '/executive-brief',
    secondaryCtaText: 'Discuss Mandate',
    secondaryCtaLink: '/contact',
    imageUrl:
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1200&auto=format&fit=crop',
    tags: ['Systems Architecture', 'Fractional COO', 'Turnaround Strategy', 'Cross-Disciplinary'],
    active: true,
    order: 5,
  },
];

export const defaultSiteSettings: SiteSettings = {
  siteName: 'Kel Nnorom',
  siteTitle: 'Kel Nnorom | Growth Strategist',
  siteDescription:
    'Kel Nnorom is a cross-functional operations and growth strategist working across digital systems, business operations, technology, data, monetization, logistics and supply chain.',
  tagline: 'I turn complex operations into measurable growth.',
  contactEmail: 'contact@kelnnorom.com',
  contactPhone: '+234 805 439 7057',
  whatsappNumber: '+2348054397057',
  whatsappPrefillText: 'Hello Kel, I would like to discuss an operational advisory inquiry.',
  socials: {
    x: 'https://x.com/Kelnnorom',
    facebook: 'https://facebook.com/Kelnnorom',
    instagram: 'https://instagram.com/Kelnnorom',
    linkedin: 'https://linkedin.com/in/kelnnorom',
  },
  executiveQuote: '...by all means, dream always.',
  availableForAdvisory: true,
  enableQuickAccessDemo: false,
  quickAccessPresets: [
    {
      id: 'preset-superadmin-user',
      label: 'Super Admin (User Master)',
      email: 'imowideweb@gmail.com',
      role: 'super_admin',
      description: 'Superadmin backend access - accounts, frontend & multimedia control',
      badge: 'Super Admin',
    },
    {
      id: 'preset-superadmin',
      label: 'Kel Nnorom (Super Admin)',
      email: 'superadmin@kelnnorom.com',
      role: 'super_admin',
      description: 'Full platform control, user management & database tools',
      badge: 'Master Admin',
    },
    {
      id: 'preset-contentadmin',
      label: 'Editorial Administrator',
      email: 'admin@kelnnorom.com',
      role: 'admin',
      description: 'Manage case studies, sliders, insights, media & content',
      badge: 'Content Lead',
    },
    {
      id: 'preset-editor',
      label: 'Strategy Contributor',
      email: 'editor@kelnnorom.com',
      role: 'editor',
      description: 'Draft essays, metrics updates, and multimedia assets',
      badge: 'Contributor',
    },
  ],
  otpExpiryMinutes: 10,
  securityNoticeText: 'Access codes are cryptographically generated and valid for 10 minutes.',

  // Superadmin Favicon & Assets
  faviconUrl: '/favicon.png',
  faviconAppleTouchUrl: '/apple-touch-icon.png',
  logoEmblemUrl: '/favicon.png',

  // Superadmin SEO Operations Setup
  canonicalUrl: 'https://www.kelnnorom.com',
  defaultOgImageUrl: 'https://www.kelnnorom.com/og-image.jpg',
  googleSiteVerification: 'google-site-verification=kn_seo_prod_verification_2026',
  bingSiteVerification: 'msvalidate.01=7A3B91C4920E83D5',
  googleAnalyticsId: 'G-6J6W9EEV8C',
  authorDefault: 'Kel Nnorom',
  metaKeywords: 'Kel Nnorom, Operations Strategist, Growth Strategist, Digital Transformation, Supply Chain Optimization, Fleet Operations, Digital Asset Management, SEO Strategy, Business Turnaround, Operations Architecture',
  robotsTxt: 'User-agent: *\nAllow: /\nDisallow: /admin/\nDisallow: /login\nSitemap: https://www.kelnnorom.com/sitemap.xml',
  sitemapUrl: 'https://www.kelnnorom.com/sitemap.xml',
  enableStructuredSchema: true,

  // Superadmin Front-End Customization & Appearance Suite
  themeAccent: 'gold',
  enableAnnouncementBar: false,
  announcementText: 'Strategic Operational Advisory Openings: Engaging select mandates across Africa & EMEA.',
  announcementBadge: 'ADVISORY NOTICE',
  announcementLink: '/contact',
  announcementCtaText: 'Inquire Now',

  // Hero Front-End Narrative & Actions
  heroEyebrow: 'Cross-Functional Operations & Growth Strategist',
  heroHeadline: 'I turn complex operations into',
  heroHeadlineHighlight: 'measurable growth',
  heroSubheadline: 'Strategy. Digital systems. Operations. Technology. Data. Revenue. People. I work where these disciplines converge—architecting operating models, transforming complex businesses, and aligning capabilities to strategy.',
  heroPitchPoint1: 'Strategy. Digital systems. Operations. Technology. Data. Revenue. People.',
  heroPitchPoint2: 'I work where these disciplines converge—architecting operating models, transforming complex businesses, and aligning capabilities to strategy. I turn complexity into scalable systems that unlock growth, strengthen performance, improve resilience, and create sustainable competitive advantage.',
  heroPrimaryCtaText: 'Explore the Work',
  heroPrimaryCtaLink: '/work',
  heroSecondaryCtaText: "Let's Build Something",
  heroSecondaryCtaLink: '/contact',
  heroBriefCtaText: 'Executive Brief (60-sec)',
  heroBriefCtaLink: '/executive-brief',
  heroCredentialsYears: '15+ years',
  heroCredentialsDescription: '15+ years operating across digital, commercial, technology and physical systems.',

  // Front-End Modular Homepage Sections Visibility
  homepageSections: {
    showHero: true,
    showHeroSliders: true,
    showCredibilityMetrics: true,
    showUncommonAdvantage: true,
    showOperatingRange: true,
    showCareerEvolution: true,
    showFeaturedCaseStudies: true,
    showOperatingStack: true,
    showHowIThink: true,
    showOperatingPhilosophy: true,
    showProfessionalEcosystem: true,
    showFeaturedInsights: true,
    showContactCta: true,
  },

  // Footer & Front-End Branding
  footerCopyrightText: 'Kel Nnorom. All rights reserved.',
  footerBadgeText: 'OPERATIONS & GROWTH ARCHITECT',
  footerQuoteText: '...by all means, dream always.',
};
